### ISSUE TITLE
Newest LC API totally bugged

### ISSUE THREAD

**Issue by Slydylan** [u-2018/LC-API#45] opened 2023-12-26 04:47 UTC
So, every version after 3.0.0 of LC API has been absolutely bugged for me. The networking error seems to cause god mode for the player, but in the newest version you cannot test if the god mode has been fixed or not because the game won't go past the ship lobby.
If terminal API is installed, the terminal is outright broken, can't be used, the ship lever can't be pulled, and the ship has 3 dummy characters titled '#Player '.
In the 3.0.0 version of LC API legacy asset loading would fix the mod incompatibilities but would not fix god mode.
I don't know this is pretty worrying I am staying with 2.1.2-2.2.0 those both seem to work well with varying levels of results in terms of unnecessary errors. Obviously the new LC API loads much better with the bundle loading fixed. None of the old versions have fixed this.
Seems like a bit of a mess y'all

edit: yes, before anyone asks, i ran each updated version of LC API by itself with no other mods and got the same errors. There is an error over all 3 where it says it cannot read the archive header of the networking file, it made it seem like a system permissions thing but i checked and nothing in here is running in anything other than administrator mode. but the newest LC API seems to have even more problems. It seems a little weird that features are being added while a game breaking bug persists over multiple versions..

**Comment by steven4547466** [comment] 2023-12-26 06:00
> but the newest LC API seems to have even more problems. It seems a little weird that features are being added while a game breaking bug persists over multiple versions..

You'll have to actually tell me what the bugs are so I can fix them as I have not had a single bug while testing. I haven't had god mode, there are no dummy players, 99% of bugs are caused by mods not being up to date with the newest LCAPI version.

If you can produce a video using the latest LC API version and no other mods other than the bepinex pack, I will fix them, but the issues you are bringing up do not show up in testing. I will leave this issue open for a couple days for you to give reproduction steps, but as it currently stands, I have not seen a single one of these issues you mention.

Here's a video that shows me downloading the latest version and testing it, and you'll find no god mode, and no dummy players:

https://oliy.is-just-a.dev/lcapi.mp4

**Comment by Slydylan** [comment] 2023-12-26 06:05
The only thing I can think of is that you guys have another api or some developer pack, some sort of syntax in your computer that we are missing because I am not the only one having this problem with vanilla. I've run your mod exact same way and I end up in god mode

**Comment by Slydylan** [comment] 2023-12-26 06:06
Wait a minute. This is for thunderstore only??
There are lots of mods built on the updated bepinex which is not the one you are using there. That is Bepinex 5.21. I have to run bepinex 5.22, and I manage everything manually.

**Comment by Slydylan** [comment] 2023-12-26 06:07
Your old LC API versions run fine with bepinex 5.22. I suppose this would be the problem as I can't test your mod without it anyways.

**Comment by steven4547466** [comment] 2023-12-26 06:10
![dk6ixk_17952 1](https://github.com/u-2018/LC-API/assets/23726534/1ac36398-64c7-4dd7-8a27-a59afa18ca07)
This is my bepinex pack version, it's also the latest:
![7st8w6_17953 1](https://github.com/u-2018/LC-API/assets/23726534/774745e7-6471-484b-90e7-45020f8f9d68)

I develop for the target r2modman as that's what the average person is using, I have download stats for thunderstore and I can verify that they would dwarf any manual downloading stats, so targeting the mod manager is the best way to keep the mod working for them as they would more than likely auto update.

**Comment by steven4547466** [comment] 2023-12-26 06:10
I'm not using any developer version as you can see in the video I had just downloaded it from r2modman.

**Comment by steven4547466** [comment] 2023-12-26 06:14
Important question, are you using LAN or Online?

**Comment by Slydylan** [comment] 2023-12-26 06:30
Online. 
Again man I'm telling you we're not using the same version of Bepinex. I have Bepinex 5.22
Bepinex 5.22 doesn't exist on Thunderstore.
Please update LC API for the updated Bepinex otherwise the only way for a mod to be compatible with your API is to roll back to 5.21
edit:
bepinex 5.22 https://github.com/BepInEx/BepInEx/releases/tag/v5.4.22
thunderstore is surprisingly trash. I don't doubt that the creator of bepinex doesn't even care to put it on thunderstore any more. And noone else can do it because the dependency relies on a team name tag which everyone would have to use or the mod no longer works.
Nexus mods exist.. Bepinex 5.22 is easy enough to use manually. Idk. We atleast need this API up to date with the new bepinex or they can't be used together and that creates a big hole in the order of operations for both creators and users

**Comment by zz2108828** [comment] 2023-12-26 06:31
Put the bundle file in the zip into the same directory as the DLL

**Comment by Slydylan** [comment] 2023-12-26 06:31
shows me a picture of his bepinex 5.21 version. That's not the latest version of Bepinex my friend......
https://github.com/BepInEx/BepInEx/releases

**Comment by Slydylan** [comment] 2023-12-26 06:33
> Put the bundle file in the zip into the same directory as the DLL

My eyes want to roll into the back of my head right now.
Do you mean the bundle folder because I drag and drop the plugins folder and don't alter the directory whatsoever.
Edit: Distinctly remember putting the networking file into the plugins directory and also trying it in the bundles folder and that does not create any changes

**Comment by Slydylan** [comment] 2023-12-26 06:42
> I'm not using any developer version as you can see in the video I had just downloaded it from r2modman.

Updated bepinex should be backwards compatible but as it stands now your API is no longer usable with the actual up to date bepinex. r2modman can't use the updated version because it is entirely dependent on thunderstore which is a rabbit hole I don't want to waste another 5 minutes on tbh

It has nothing to do with being on LAN or online it's just something wrong with the loading for my version of bepinex. I can't roll back to yours, the old version brings up errors in my build.

**Comment by catgocri** [comment] 2023-12-26 13:44
i did some testing and turns out I only get this error when I use a manual installation of BepInEx 5.4.21 and not launching modded through thunderstore.

**Comment by steven4547466** [comment] 2023-12-26 15:42
> Please update LC API for the updated Bepinex otherwise the only way for a mod to be compatible with your API is to roll back to 5.21

I am developing targeting thunderstore mod manager (or r2modman) users as they are the main userbase. I will be developing for whatever bepinex is on thunderstore. I'm sorry if this inconveniences you, but the download stats for the mod provided through thunderstore show that the majority of users are using either thunderstore manager or r2modman. Releasing an update to a bepinex version not on either is not on my todo list as it will break for those people.

If you can provide reproduction using r2modman or thunderstore manager I will be more than happy to assist in fixing, but as it stands you are using an unsupported version of bepinex for the plugin and using manual installation, neither of which I can provide support for while maintaining the target userbase.

I'm closing and locking this. Open a new issue if you encounter an issue while using the targeted supported versions and installations.

**Closed as not planned by steven4547466** 2023-12-26 15:42 UTC
